// AUTO-GENERATED by scripts/generate_ts_types.py
// Do not edit manually. Run 'python scripts/generate_ts_types.py' to regenerate.


export interface AddBookmarkRequest {
  bookId: string;
  chapterIndex: number;
  position: number;
  note?: any;
}

export interface AddOpenAIKeyRequest {
  key: string;
}

export interface AddVocabularyWordRequest {
  word: string;
  translation: string;
  language?: string;
  bookId?: string | null;
  context?: string | null;
  difficulty?: string | null;
}

export interface AddVocabularyWordResponse {
  success: boolean;
  id: string;
  word: string;
  translation: string;
  language: string;
}

export interface AdminStatusResponse {
  userId: string;
  isAdmin: boolean;
  memberships: Record<string, any>[];
  error?: string | null;
}

export interface Book {
  id: string;
  title: string;
  fileType?: any;
  driveFileId?: any;
  filename?: any;
  source?: any;
  path?: any;
}

export interface Bookmark {
  id: any;
  bookId: string;
  chapterIndex: number;
  position: number;
  note?: any;
  createdAt?: any;
}

export interface Deck {
  id: string;
  name: string;
  words?: number | null;
}

export interface DriveFile {
  id: string;
  name: string;
  mimeType?: string | null;
  modifiedTime?: string | null;
  size?: string | null;
  webViewLink?: string | null;
  iconLink?: string | null;
  thumbnailLink?: string | null;
  hasThumbnail?: boolean | null;
}

export interface DueCard {
  id: string;
  term: string;
  meaning: string;
}

export interface FetchDueCardsGoogleOAuthRequest {
  offset?: number;
}

export interface GetBookmarksRequest {
  bookId: string;
}

export interface GetJpdbDataRequest {
  textSegments: string[];
  jpdbApiKey: string;
}

export interface GrammarInfo {
  id: string;
  title: string;
  meaning: string;
  level: string;
}

export interface GrammarValidateCandidate {
  id: string;
  sentence: string;
  before?: any;
  after?: any;
  hintSpan?: any;
}

export interface GrammarValidateMatch {
  candidateId: string;
  isMatch: boolean;
  confidence?: any;
  matchSpan?: any;
  explanation?: any;
}

export interface HealthResponse {
  clerkSecretKeyConfigured: boolean;
  clerkClientInitialized: boolean;
  service: string;
}

export interface ImportLyricsRequest {
  url: string;
}

export interface ImportedLyrics {
  title: string;
  artist: string;
  text: string;
  sourceUrl: string;
}

export interface KanjiSearchRequest {
  query: string;
}

export interface KanjiSearchResponse {
  results: any;
}

export interface KanjiSearchResult {
  kanji: string;
  meanings: any;
  jlpt?: any;
}

export interface ListFilesRequest {
  folderId?: string | null;
}

export interface ListUserDecksRequest {
  username?: string | null;
  password?: string | null;
  cookie?: string | null;
}

export interface MineWordRequest {
  vid: number;
  sid: number;
  jpdbApiKey: string;
  miningDeckId?: number | null;
  forq?: boolean | null;
  forqDeckId?: number | null;
  sentence?: string | null;
}

export interface MixRefineCandidate {
  id: string;
  spelling: string;
  reading?: any;
  meaning?: any;
}

export interface MixRefineRequest {
  textSample: string;
  ambiguousKeys?: any;
  candidatesByKey?: any;
  model?: any;
  apiKey?: any;
}

export interface MixRefineResponse {
  choices?: any;
  modelUsed?: any;
}

export interface OCRProcessResponse {
  success: boolean;
  message: string;
}

export interface OpenAIKeyListResponse {
  keys: string[];
}

export interface OpenAIKeyOperationResponse {
  success: boolean;
  poolSize: number;
}

export interface OpenAIKeyStatusResponse {
  openaiKeyConfigured: boolean;
  poolSize: number;
}

export interface ProcessedToken {
  start: number;
  length: number;
  end: number;
  card: Record<string, any>;
  rubies?: Ruby[];
}

export interface RemoveOpenAIKeyRequest {
  key: string;
}

export interface ReviewCardRequest {
  vid: number;
  sid: number;
  rating: 'nothing' | 'something' | 'hard' | 'good' | 'easy' | 'pass' | 'fail' | 'known' | 'unknown';
  jpdbApiKey: string;
}

export interface Ruby {
  text: string;
  start: number;
  length: number;
  end: number;
}

export interface SaveSettingsRequest {
  settings: any;
}

export interface SaveSettingsResponse {
  success: boolean;
}

export interface SessionInfo {
  userId: string;
  sessionId: string;
  status?: any;
}

export interface SettingsResponse {
  settings: any;
}

export interface Span {
  start: number;
  end: number;
  text?: any;
}

export interface TeachExampleIn {
  exampleId: string;
  sentence: string;
  before?: any;
  after?: any;
  matchSpan?: any;
}

export interface TeachExampleOut {
  exampleId: string;
  translation?: any;
  breakdown?: any;
  usageNote?: any;
  contrast?: any;
}

export interface TeachExamplesRequest {
  grammar: any;
  examples: any;
  model?: string;
  apiKey?: any;
}

export interface TeachExamplesResponse {
  teachings: any;
}

export interface ToggleJlptRequest {
  enabled: boolean;
}

export interface ToggleJlptResponse {
  success: boolean;
  jlptHighlightingEnabled: boolean;
}

export interface ToggleMasteredRequest {
  mastered: boolean;
}

export interface TokenResponse {
  accessToken: string;
  expiresIn: number;
}

export interface TranslateRequest {
  content: string;
  targetLang?: string | null;
  sourceLang?: string | null;
  model?: string | null;
  apiKey?: string | null;
  cefrLevel?: string | null;
  stream?: boolean | null;
  useCefr?: boolean | null;
  translationService?: string | null;
}

export interface TranslateResponse {
  translatedText: string;
  modelUsed?: string | null;
}

export interface UpdateKanjiJlptRequest {
  kanji: string;
  jlptLevel?: any;
}

export interface UpdateKanjiJlptResponse {
  success: boolean;
  kanji: string;
  oldJlpt: any;
  newJlpt: any;
}

export interface UpdateWordStateRequest {
  vid: number;
  sid: number;
  flag: 'blacklist' | 'never-forget' | 'forq';
  state: any;
  jpdbApiKey: string;
  blacklistDeckId?: number | null;
  neverForgetDeckId?: number | null;
  forqDeckId?: number | null;
}

export interface UploadFileRequest {
  folderId?: string | null;
  filename: string;
  mimetype: string;
}

export interface UserInfo {
  id: string;
  email?: any;
  firstName?: any;
  lastName?: any;
  username?: any;
  imageUrl?: any;
  createdAt?: any;
}

export interface ValidateExamplesRequest {
  grammar: any;
  candidates: any;
  maxResults?: number;
  model?: string;
  apiKey?: any;
}

export interface ValidateExamplesResponse {
  matches: any;
}

export interface Vocabulary {
  id: string;
  word: string;
  translation: string;
  language: string;
  bookId?: string | null;
  context?: string | null;
  difficulty?: string | null;
  mastered?: boolean;
  createdAt?: string | null;
}

export interface VocabularyListResponse {
  vocabulary: Vocabulary[];
}
