// AUTO-GENERATED by scripts/generate_ts_types.py (pilot)
// Replace with pydantic-to-typescript/datamodel-code-generator later.
// Do not edit manually.

export interface TranslateRequest {
  content: string;
  target_lang?: string;
  source_lang?: string | null;
  model?: string;
  api_key?: string | null;
  cefr_level?: string | null;
  stream?: boolean;
  use_cefr?: boolean;
  translation_service?: string;
}

export interface TranslateResponse {
  translated_text: string;
  model_used?: string | null;
}

export interface DueCard {
  id: string;
  term: string;
  meaning: string;
}

export interface FetchDueCardsRequest {
  username?: string;
  password?: string;
  cookie?: string;
}

export interface Deck {
  id: string;
  name: string;
  words?: number | null;
}

export interface ListUserDecksRequest {
  username?: string;
  password?: string;
  cookie?: string;
}

export type ListUserDecksResponse = Deck[];

export interface GetJpdbDataRequest {
  text_segments: string[];
  jpdb_api_key: string;
}

export interface Ruby {
  text: string;
  start: number;
  length: number;
  end: number;
}

export interface ProcessedToken {
  start: number;
  length: number;
  end: number;
  card: Record<string, any>;
  rubies: Ruby[];
}

export interface MineWordRequest {
  vid: number;
  sid: number;
  jpdb_api_key: string;
  mining_deck_id?: number;
  forq?: boolean;
  sentence?: string;
  forq_deck_id?: number;
}

export type UpdateFlag = 'blacklist' | 'never-forget' | 'forq';

export interface UpdateWordStateRequest {
  vid: number;
  sid: number;
  flag: UpdateFlag;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  state: any;
  jpdb_api_key: string;
  blacklist_deck_id?: number;
  never_forget_deck_id?: number;
  forq_deck_id?: number;
}

export type ReviewRating =
  | 'nothing' | 'something' | 'hard' | 'good' | 'easy'
  | 'pass' | 'fail' | 'known' | 'unknown';

export interface ReviewCardRequest {
  vid: number;
  sid: number;
  rating: ReviewRating;
  jpdb_api_key: string;
}

export interface Bookmark {
  id: string | number;
  bookId: string;
  chapterIndex: number;
  position: number;
  note?: string | null;
  createdAt?: string | null;
}

export interface GetBookmarksRequest {
  bookId: string;
}

export interface AddBookmarkRequest {
  bookId: string;
  chapterIndex: number;
  position: number;
  note?: string;
}
