#!/usr/bin/env python3
"""
TypeScript type generator from Pydantic schemas.

This script scans all domain schemas and generates TypeScript interfaces
automatically from Pydantic models.
"""

import sys
import importlib.util
from pathlib import Path
from typing import Any, Dict, Set
import re

ROOT = Path(__file__).resolve().parents[1]
TARGET = ROOT / "frontend" / "src" / "types" / "api.ts"
BACKEND_DIR = ROOT / "backend"

# Add backend to path for imports
sys.path.insert(0, str(BACKEND_DIR))

TS_HEADER = """// AUTO-GENERATED by scripts/generate_ts_types.py
// Do not edit manually. Run 'python scripts/generate_ts_types.py' to regenerate.
"""


def python_type_to_ts(python_type: Any, optional: bool = False) -> str:
    """Convert Python type to TypeScript type."""
    origin = getattr(python_type, '__origin__', None)
    args = getattr(python_type, '__args__', None)
    
    # Handle Union types (including Optional)
    if origin is type(None) or (hasattr(python_type, '__origin__') and python_type.__origin__ is type(None)):
        return "null"
    
    if origin is not None:
        # Handle Optional[type] -> type | null
        if origin.__name__ == 'Union' and args:
            non_none_args = [arg for arg in args if arg is not type(None)]
            if len(non_none_args) == 1:
                ts_type = python_type_to_ts(non_none_args[0])
                return f"{ts_type} | null" if optional else ts_type
            else:
                # Multiple union types
                types = [python_type_to_ts(arg) for arg in non_none_args]
                return " | ".join(types)
        
        # Handle List[type] -> type[]
        if origin.__name__ == 'list' or origin is list:
            if args:
                item_type = python_type_to_ts(args[0])
                return f"{item_type}[]"
            return "any[]"
        
        # Handle Dict[str, type] -> Record<string, type>
        if origin.__name__ == 'dict' or origin is dict:
            if args and len(args) >= 2:
                value_type = python_type_to_ts(args[1])
                return f"Record<string, {value_type}>"
            return "Record<string, any>"
        
        # Handle Literal types
        if origin.__name__ == 'Literal':
            if args:
                literals = [repr(arg) for arg in args]
                return " | ".join(literals)
    
    # Handle built-in types
    type_map = {
        str: "string",
        int: "number",
        float: "number",
        bool: "boolean",
        dict: "Record<string, any>",
        list: "any[]",
        Any: "any",
    }
    
    # Check if it's a built-in type
    if python_type in type_map:
        return type_map[python_type]
    
    # Check if it's a class (Pydantic model)
    if hasattr(python_type, '__name__'):
        return python_type.__name__
    
    return "any"


def get_field_type(field_info: Any, model_name: str) -> tuple[str, bool]:
    """Get TypeScript type and optional flag for a Pydantic field."""
    annotation = field_info.annotation
    
    # Check if field is optional
    optional = field_info.is_required() is False
    
    ts_type = python_type_to_ts(annotation, optional)
    
    return ts_type, optional


def generate_interface(model: Any, model_name: str) -> str:
    """Generate TypeScript interface from Pydantic model."""
    lines = [f"export interface {model_name} {{"]
    
    for field_name, field_info in model.model_fields.items():
        ts_type, optional = get_field_type(field_info, model_name)
        
        # Handle snake_case to camelCase conversion
        ts_field_name = snake_to_camel(field_name)
        
        optional_marker = "?" if optional else ""
        lines.append(f"  {ts_field_name}{optional_marker}: {ts_type};")
    
    lines.append("}")
    return "\n".join(lines)


def snake_to_camel(snake_str: str) -> str:
    """Convert snake_case to camelCase."""
    components = snake_str.split('_')
    return components[0] + ''.join(x.title() for x in components[1:])


def scan_domain_schemas() -> Dict[str, Any]:
    """Scan all domain schema files and collect Pydantic models."""
    models: Dict[str, Any] = {}
    domains_dir = BACKEND_DIR / "app" / "domains"
    
    for domain_dir in domains_dir.iterdir():
        if not domain_dir.is_dir():
            continue
        
        schemas_file = domain_dir / "schemas.py"
        if not schemas_file.exists():
            continue
        
        try:
            # Import the schemas module
            spec = importlib.util.spec_from_file_location(
                f"domains.{domain_dir.name}.schemas",
                schemas_file
            )
            if spec is None or spec.loader is None:
                continue
            
            module = importlib.util.module_from_spec(spec)
            spec.loader.exec_module(module)
            
            # Find all BaseModel subclasses
            for name in dir(module):
                obj = getattr(module, name)
                if (isinstance(obj, type) and 
                    hasattr(obj, '__bases__') and
                    any('BaseModel' in str(base) for base in obj.__bases__) and
                    hasattr(obj, 'model_fields')):
                    models[name] = obj
                    
        except Exception as e:
            print(f"Warning: Could not load schemas from {schemas_file}: {e}", file=sys.stderr)
            continue
    
    return models


def main() -> None:
    """Generate TypeScript types from Pydantic schemas."""
    print("Scanning domain schemas...")
    models = scan_domain_schemas()
    
    if not models:
        print("Warning: No Pydantic models found. Using fallback types.")
        # Fallback to existing types
        return
    
    print(f"Found {len(models)} models: {', '.join(models.keys())}")
    
    # Generate TypeScript interfaces
    interfaces = []
    for model_name, model in sorted(models.items()):
        try:
            interface = generate_interface(model, model_name)
            interfaces.append(interface)
        except Exception as e:
            print(f"Warning: Could not generate interface for {model_name}: {e}", file=sys.stderr)
            continue
    
    # Write to file
    TARGET.parent.mkdir(parents=True, exist_ok=True)
    content = TS_HEADER + "\n\n" + "\n\n".join(interfaces) + "\n"
    TARGET.write_text(content, encoding="utf-8")
    print(f"Generated {len(interfaces)} TypeScript interfaces in {TARGET}")


if __name__ == "__main__":
    main()
