name: Deploy to Cloud Run via Cloud Build

on:
  push:
    branches:
      - main
      - test-deploy

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'  # needed for OIDC

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/49477009498/locations/global/workloadIdentityPools/github-pool/providers/github-provider
          # The service account you created for CI/CD
          service_account: github-actions@floofgg.iam.gserviceaccount.com

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: floofgg

      - name: Determine Environment and Service Name
        id: vars
        run: |
          if [[ "${{ github.ref_name }}" == "main" ]]; then
            echo "SERVICE_NAME=progressive-reader" >> $GITHUB_OUTPUT
            echo "ENVIRONMENT=prod" >> $GITHUB_OUTPUT
          elif [[ "${{ github.ref_name }}" == "test-deploy" ]]; then
            echo "SERVICE_NAME=progressive-reader-dev" >> $GITHUB_OUTPUT
            echo "ENVIRONMENT=dev" >> $GITHUB_OUTPUT
          else
            echo "Skipping deployment for branch ${{ github.ref_name }}"
            exit 0
          fi

      - name: Submit build to Google Cloud Build
        if: steps.vars.outputs.SERVICE_NAME != ''
        run: |
          gcloud builds submit \
            --project=floofgg \
            --config=cloudbuild.yaml \
            --substitutions=COMMIT_SHA=${{ github.sha }},_SERVICE_NAME=${{ steps.vars.outputs.SERVICE_NAME }},_ENVIRONMENT=${{ steps.vars.outputs.ENVIRONMENT }} \
            --gcs-log-dir=gs://floofgg_cloudbuild/logs \
            .
